### ISSUE TITLE
Publish latest version of Gremlin client

### ISSUE THREAD

**Issue by charlieduong94** [jbmusso/gremlin-javascript#102]
@jbmusso Any chance you could publish a new version of the Gremlin client? We are currently using a temporary fork of this project that contains [this](https://github.com/jbmusso/gremlin-javascript/pull/101) addition. I'm sure other users would benefit from having this change as well.

**Comment by jbmusso** [comment]
Just published v2.7.0. Let me know if anything goes wrong.
