### ISSUE TITLE
Is direct graph management possible?

### ISSUE THREAD

**Issue by grreeenn** [jbmusso/gremlin-javascript#106]
Hello,

Thanks a lot for bringing the Gremlin power to JS, incredible work! :) I guess that I have more a question than an issue.

Is it possible to perform management operations on the graph, like adding property fields or indices? I saw that it's possible to make use of conventional Gremlin object names (as g and graph); the conventional name for management object in gremlin console is 'mgmt', but 
`const uuid = await gremlin`mgmt.makePropertyKey('uuid').dataType(UUID.class).cardinality(Cardinality.SINGLE).make()`;`
returns "No such property: mgmt for class: Script5 (Error 597)". 

Do I miss something obvious, or it's just not available at the moment?

(Using JanusGraph 0.2.0-hadoop2 with janusgraph-cassandra-es default config)

Thank you once again :)

**Comment by jbmusso** [comment]
Hello, thanks for the kind words!

Unless you're using `session` mode and already instantiated the management instance before, I think you need to instantiate the management instance in the same query. This should help:
```javascript
const uuid = await gremlin`
  mgmt = graph.openManagement();
  mgmt.makePropertyKey('uuid').dataType(UUID.class).cardinality(Cardinality.SINGLE).make();
`;
```

Hopefully this helps. Note: I slightly edited your code snippet for formatting reasons.
