### ISSUE TITLE
'Error: socket hang up' when trying to use the library

### ISSUE THREAD

**Issue by oren** [jbmusso/gremlin-javascript#14]
Steps to reproduce:
```
git clone https://github.com/oren/titan.git
cd titan
docker-compose up
npm install
node get-all.js

Error:
{ [Error: socket hang up]
  code: 'ECONNRESET',
  target:
   { domain: null,
     _events:
      { open: [Object],
        error: [Object],
        message: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _socket: null,
     _ultron: null,
     _closeReceived: false,
     bytesReceived: 0,
     readyState: 0,
     supports: { binary: true },
     extensions: {},
     _isServer: false,
     url: 'ws://localhost:8182',
     protocolVersion: 13
  }
}
```

by the way, gremlin console seems to be fine:
```
bin/gremlin

plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
07:48:40 INFO  org.apache.tinkerpop.gremlin.hadoop.structure.HadoopGraph  - HADOOP_GREMLIN_LIBS is set to: /opt/titan-0.9.0-M2-hadoop1/bin/../lib
plugin activated: tinkerpop.hadoop
plugin activated: tinkerpop.tinkergraph
plugin activated: aurelius.titan
gremlin>  :remote connect tinkerpop.server conf/remote.yaml
==>Connected - localhost/127.0.0.1:8182
gremlin> :> graph.addVertex("name", "stephen")
==>v[4160]
gremlin> :> g.V().values('name')
==>stephen
gremlin>
```

I also posted it on the [mailing list](https://groups.google.com/forum/#!topic/aureliusgraphs/DT5GONk3eoQ).

**Comment by jbmusso** [comment]
Thanks for reporting this issue, I'll have a look at your repository and see if I can provide support.

**Comment by oren** [comment]
I figure it out. i forgot to open the ports in docker.

I still have issues with adding vertex to the graph, but I am getting help from phani1kumar -
https://github.com/phani1kumar/docker-titan/issues/4#issuecomment-138634096

btw, it will be awesome to have a few more examples for basic operations - add vertex and edges etc.

**Comment by jbmusso** [comment]
I couldn't start your container because it looks like the `docker-compose.yml` file is missing.

However, by looking at your `Dockerfile` and `package.json` files, it looks like you're trying to connect to Titan v0.5.4 with gRex (HTTP client). I kind of fail to see how you managed to get this WebSocket error: could you please double-check your git repository so I can reproduce the issue you're having?

**Comment by oren** [comment]
I created a new repository for reproducing my issue:
https://github.com/oren/titan-gremlin-client
You should be able to follow the exact steps in  readme.

Notice that there is a folder called 'titan' where the Dockerfile exist.
Also, if you are on a mac you should use `docker-machine ip` or `boot2docker ip` instead of localhost (in bin/test) but i think everything else should be the same. I am on ubuntu btw.

Thank you!

**Comment by oren** [comment]
I am closing this since I was able to run again titan 1.0.0 and without docker. if i'll ever try to use the dockerized approach, i'll update this issue.
