### ISSUE TITLE
Empty array

### ISSUE THREAD

**Issue by adurrive** [jbmusso/gremlin-javascript#17]
Hello, the callback is not called when the response array is empty. 

```javascript
var client = gremlin.createClient();

client.execute('g.V().limit(0)', function(err, results) {
  console.log('hello');
});
```

**Comment by jbmusso** [comment]
Thanks for reporting this. I'm going to bed right now so I'll have a look at it tomorrow :P.

**Comment by adurrive** [comment]
Thanks! I've fixed it by pushing a null value on the 204 status code in GremlinClient.prototype.handleMessage. But I'm not sure of the implications.

**Comment by jbmusso** [comment]
Pushing `null` properly terminates the stream and I can't see any side-effect by doing so. I just pushed v1.0.2 with this fix on npm.
