### ISSUE TITLE
Id bound parameter not working

### ISSUE THREAD

**Issue by realolliebee** [jbmusso/gremlin-javascript#23]
// Doesn't work
client.execute("g.V(id).valueMap()", {id:53408}, function(err, results) {
    console.log(results);
    next();
});

// Works
client.execute("g.V(53408).valueMap()", function(err, results) {
    console.log(results);
    next();
});

**Comment by realolliebee** [comment]
Also, the returned err is null.

**Comment by jbmusso** [comment]
Thanks for spotting this. Which graph database (and version) are you using?

**Comment by realolliebee** [comment]
I'm using Titan 1.0.  DockerFile repo here: https://github.com/realolliebee/db

**Comment by jbmusso** [comment]
Do you get any warnings/errors in the gremlin server console by chance? (I didn't have time to try your Dockerfile yet, sorry).
Otherwise, I'm guessing an issue with the type of `id` where Titan expects a long and gremlin server interprets that `id` as an integer.

**Comment by realolliebee** [comment]
No errors in the gremlin server terminal.  Do you know if there's some advanced error reporting I can enable?

**Comment by jbmusso** [comment]
You can try starting gremlin-server with the `-v` (verbose) flag.

**Comment by realolliebee** [comment]
The verbose flag didn't help, but I figured it out anyway. It only fails  for 'id' and 'ID' (though not for 'Id' or 'iD').  I'm guessing 'id' is reserved, similar to 'label'.  I'll close the issue, but you should probably update your bound parameters example (and maybe make a note about id):
https://github.com/jbmusso/gremlin-javascript#adding-bound-parameters-to-your-scripts

Thanks for the help!

**Comment by PommeVerte** [comment]
There are a few new reserved keys in titan 1.0 . `key` is another one.

**Comment by realolliebee** [comment]
Thanks @PommeVerte, do you know if that's documented anywhere?

**Comment by PommeVerte** [comment]
Not that I could find. I also asked about a full list but haven't heard back yet. I would assume the following are reserved: 
- `key`
- `id`
- `label`
- `value` (not sure)
