### ISSUE TITLE
Emit a "connectionError" event when the WebSocket connection fails

### ISSUE THREAD

**Issue by davidrapin** [jbmusso/gremlin-javascript#24]
Replace 
```
  this.ws.onerror = function(e) {
    console.log('Error:', e);
  };
```

with

```
  this.ws.onerror = function(e) {
    this.emit('connectionError', e);
  };
```

Otherwise there is no way to way to know that the connection failed.

**Comment by jbmusso** [comment]
I just pushed a commit. I take a lot of inspiration from node_redis so I named the event `error` (see https://github.com/NodeRedis/node_redis#connection-events).

I also need to add a way to automatically reconnect. I think using https://www.npmjs.com/package/retry could help. I still need to think that through.

**Comment by davidrapin** [comment]
Thank you for the swift fix. However, the `'error'` event is already used for query errors, so any use-case that I can think of would need an `if` inside the event handler to differentiate connection errors from query errors. 

Example:
```JavaScript
function connectClient = function(host, port, done) {
  var client = gremlin.createClient(host, port);
  client.on('connect', function() {
    done(null);
  }).on('error', function(err) {
    // could be a query error after connection has already succeeded
   if (!client.connected) {
     done(err);
   }
  });
```

I believe it would be much simpler to have different event names for connection errors and query errors.

**Comment by jbmusso** [comment]
Ah, I see what you mean. Let me think that through, there might indeed be a better way to name that event or to distinguish between client events and query (= `ReadableStream`) events.

**Comment by jbmusso** [comment]
I'm thinking about adding a `disconnect` event at the client level (= Websocket disconnection errors) in order to distinguish from the current `error` event which can be emitted by result steams when using the `.stream()` API. Unless I'm mistaken, the client instance doesn't emit an `error` event should a stream error actually occur, though I might be wrong on that one - I'll have to check/test that.

Feel free to provide feedback!

**Comment by davidrapin** [comment]
I'm no t sure about the ` disconnect` semantics as this can happen if connection never took place (e.g.: tried to connect but failed because the provided port was wrong).
