### ISSUE TITLE
Ended commands not removed from the pending command list 

### ISSUE THREAD

**Issue by pavb74** [jbmusso/gremlin-javascript#27]
gremlinclient internal command list is not cleaned properly for commands in error or with no content.
The commands are removed from the list only if the server HTTP return code is 200.
In all the others cases the commands are kept
It causes new error events on commands already processed during disconnection.
I may be wrong but I also would delete the commands for code 204 and errors.

**Comment by jbmusso** [comment]
Thanks! I'll have a look into it shortly.

On Thursday, 3 March 2016, pavb74 <notifications@github.com> wrote:

> gremlinclient internal command list is not cleaned properly for commands
> in error or with no content.
> The commands are removed from the list only if the server HTTP return code
> is 200.
> In all the others cases the commands are kept
> It causes new error events on commands already processed during
> disconnection.
> I may be wrong but I also would delete the commands for code 204 and
> errors.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbmusso/gremlin-javascript/issues/27>.
>


-- 
Jean-Baptiste

**Comment by jbmusso** [comment]
Wow, I can't believe I left that here - I thought I had fixed that long ago. I'll need to write some tests before I commit something, and I will be off for about a week starting tomorrow. I think [that part of the code](https://github.com/jbmusso/gremlin-javascript/blob/98ee2f508d19bf804573826ed5e1fa553ad0d137/src/GremlinClient.js#L80L95) might need a bit of refactoring as well.

**Comment by jbmusso** [comment]
Until I publish something clean(er) on npm, you can set `"gremlin": "jbmusso/gremlin-javascript#e7cdf31"` in your `package.json`. Tests passed locally so I don't think I broke something.

**Comment by pavb74** [comment]
Thanks for your feedback I will try that this afternoon.

**Comment by jbmusso** [comment]
Added in v2.2.0
