### ISSUE TITLE
Feature request: custom websocket path

### ISSUE THREAD

**Issue by Koka** [jbmusso/gremlin-javascript#32]
Currently there is no ability to connect to websocket at some custom path like `ws://myhost:80/websockets/test/` - it might be very useful in scenarios when Nginx websocket proxy is involved.

Currently there is dirty hack that allows to do this: specifying path as part of `port` parameter in `createClient` call like `const client = Gremlin.createClient('80/websockets/test/', 'localhost');` 

I wonder if it's possible to rewrite url generation to support one additional parameter `path` so the call would be like `const client = Gremlin.createClient(80, 'localhost', '/websockets/test/');`

**Comment by jbmusso** [comment]
That's indeed a dirty hack :). I'll see if I can add this feature soon -
maybe this weekend.

On Thursday, 17 March 2016, Konstantin V. Salikhov <notifications@github.com>
wrote:

> Currently there is no ability to connect to websocket at some custom path
> like ws://myhost:80/websockets/test/ - it might be very useful in
> scenarios when Nginx websocket proxy is involved.
>
> Currently there is dirty hack that allows to do this: specifying path as
> part of port parameter in createClient call like const client =
> Gremlin.createClient('80/websockets/test/', 'localhost'); - I wonder if
> it's possible to rewrite url generation to support one additional parameter
> path so the col would be like const client = Gremlin.createClient(80,
> 'localhost', '/websockets/test/');
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jbmusso/gremlin-javascript/issues/32>
>


-- 
Jean-Baptiste

**Comment by jbmusso** [comment]
Added in v2.2.0

**Comment by Koka** [comment]
Thank you very much!

**Comment by jbmusso** [comment]
Note that you do not have to add a leading slash to the provided `path`, the client should handle this for you.
