### ISSUE TITLE
Adding Data to Gremlin?

### ISSUE THREAD

**Issue by Vani-gurnani** [jbmusso/gremlin-javascript#33]
This is great library.

Is there anyway to add data to Gremlin using this library?

How to execute queries with transactions where we have to create a Vertex First and then pass the reference of the Vertex to create an Edge ?

**Comment by jbmusso** [comment]
What do you mean by "add data to Gremlin"? You don't really "add data to Gremlin", but you use Gremlin queries to add data to a graph by sending these queries for execution on a remote Gremlin Server instance.

Providing your graph database supports transactions, you can simply send a multiline Gremlin query which mutates the graph (note the `\n` at the end of each line). The following should work (or [refer to the TinkerPop 3.1.1 documentation](http://tinkerpop.incubator.apache.org/docs/3.1.1-incubating/reference/)):

```javascript
var gremlin = require('gremlin');
var client = gremlin.createClient();
var query = 'marko = g.addVertex("name", "marko", "age", 29)\n'+
  'lop = g.addVertex("name","lop","lang","java")\n' +
  'marko.addEdge("created", lop, "weight", 0.6d)';

client.execute(query, (err, results) => {
  // Handle err or results.
});
```
This will add 2 vertices and 1 edge to the graph in a single query (one round-trip between the client and the server). The transaction should be implicitly committed and the result of the last statement will be returned (that'd be the created edge in the above example). This is the most efficient way on a network point of view.

I strongly recommend that you use ES6 template strings (strings enclosed with backticks) so you don't have to manually add `\n` and concatenate strings by hand:
```javascript
var query = `
  marko = g.addVertex("name", "marko", "age", 29)
  lop = g.addVertex("name","lop","lang","java")
  marko.addEdge("created", lop, "weight", 0.6d)
`;
```
The best way would be to use tagged template strings bound to a Gremlin client instance, see: https://github.com/jbmusso/gremlin-javascript/blob/e7cdf31348a5065f875c3a5375f1b161f12f7280/README.md#promisetemplate-mode-gremlinmaketemplatetagclient
That'd be:
```
```

You can also use the client in session mode but you'll have to manually commit the transaction. This is less efficient for you get a network roundtrip for each query sent, and you have to manually commit the transaction.
