### ISSUE TITLE
roblem using gremlin npm when running the query graph.indexQuery("searchPropIndex", "v.searchProp:Marko").vertices()*.getElemet()

### ISSUE THREAD

**Issue by ellavs1** [jbmusso/gremlin-javascript#51]
The query does not work when using titan 1.0.0 gremlin 3.0.1. I tried to convert the elements to vertexes but it did not work. I tired to use iterator() but I could not get all the vertexes only the first .

then I did g.V( graph.indexQuery(......).toArray()) , it works , but when the array is empty it turns to be g.V() and it returns all vertexes insted of empty result.

I do not want to use two queries in order to run indexQuery (Im using elastic search)/

**Comment by PommeVerte** [comment]
Can you share the errors you get?
