### ISSUE TITLE
No results when tree() step added to script

### ISSUE THREAD

**Issue by davidcrouch** [jbmusso/gremlin-javascript#53]
I have simplified a traversal to "g.V(1).out().tree()" and "g.V(1).out().tree().next()" and am not getting any results. There are no errors in the server log and I have verified that results are not being passed through the default 'executeHandler'. It does work if I remove the "tree()" step. 

I'm not sure if I'm doing something wrong or it is a bug.

**Comment by PommeVerte** [comment]
FYI `tree()` was not supported by the `GraphSONMessageSerializer` (ie: when returning `JSON` results) until gremlin server `3.2.0-incubating` & `3.1.2-incubating` so if you're using versions prior to those then that would explain why you aren't getting anything (though the server should throw an error).

What you can do (if you can't update your server version for some reason) is use `g.V(1).out().path()` then  programmatically recreate the tree on the client end.

**Comment by davidcrouch** [comment]
Yep, that's it. I'm still running 3.0.1. I have been using path() but was trying to optimize my scripts by using tree(). Might be time to upgrade.

**Comment by gregory-h** [comment]
Running into the same issue.  

Can anyone elaborate on the upgrade path to 3.1.2 or 3.2 in the context of Titan?   Can't seem to find any leads.

**Comment by jbmusso** [comment]
Thanks for sharing this, useful tip!
