### ISSUE TITLE
Array property type?

### ISSUE THREAD

**Issue by gregory-h** [jbmusso/gremlin-javascript#54]
When I add a property with an Array data type my callback returns err 'property value [[37.7, 23.9]] is of type class java.util.ArrayList is not supported (Error 500)'. Same result if it's inline or bound, ie

client.execute( 'g.addV( "name", name, "place", [37.7,23.9] )', {name:'Home'},..
client.execute( 'g.addV( "name", name, "place", place)', {name:'Home',place:[37.7,23.9]},..

Wondering if there is another syntax for arrays or am I missing some config or ?

**Comment by dragma** [comment]
There is no ArrayList type : http://s3.thinkaurelius.com/docs/titan/1.0.0/schema.html#_property_key_data_type
Maybe you should take a better look at http://s3.thinkaurelius.com/docs/titan/1.0.0/schema.html#property-cardinality

**Comment by gregory-h** [comment]
Ah got it, thx for the clarification.
