### ISSUE TITLE
Update ws dependency to 1.x

### ISSUE THREAD

**Issue by princjef** [jbmusso/gremlin-javascript#60]
When I try to run heavy loads (many queries consecutively or concurrently) using this library with node 6.6.0, I occasionally run into issues like [this one](https://github.com/websockets/ws/issues/778) that appear to come from the underlying websockets library. When I shrinkwrap and bump the version of ws up from 0.8.0 to 1.1.1 everything still appears to work for me and the intermittent errors go away.

Is there a reason to stay on ws 0.x or can it be bumped to 1.x? It would be nice to not have to force the version up with shrinkwrap.

I can also try pulling the repo, updating and testing with the new version of ws when I have some time. I assume this is what i need to run:

```
npm run build
npm run test:node
```

**Comment by princjef** [comment]
A little extra context:

I'm using the `execute()` API for my queries and pointing to a remote Titan db running Tinkerpop 3.2.0-incubating

**Comment by jbmusso** [comment]
There is no specific reason to stick to `ws@v0.8.0`. I'll try to bump the version in the coming days. If you could send a pull request instead, that would be really cool :).

Just curious, how many concurrent requests are you executing (even approximately)?

**Comment by princjef** [comment]
I haven't been running with much concurrency (low single digits). The most recent tests where I saw it were actually running serially (100 ms gap between tests).

I should have some time later today. I'll try it out and send a PR if everything passes

**Comment by princjef** [comment]
I tried updating the dependency and running the tests, but I'm getting several failures. Here's my setup:

 * Node 6.6.0
 * TinkerGraph Gremlin server (Tinkerpop 3.2.0-incubating) running on 127.0.0.1:8182

I get 22 passing, 3 pending, and 21 failures regardless of which version of ws I use.

Is there a certain configuration/version I should be using for the tests?

**Comment by princjef** [comment]
@jbmusso I came back around to this issue while working on #73. It turns out my build issues were due to a change in the code generated by newer versions of babel, which broke the `execute()` method in certain cases, causing the tests to fail. I fixed that and now everything is working. The updated dependency isn't causing any problems

**Comment by princjef** [comment]
fixed by #74
