### ISSUE TITLE
hang during test

### ISSUE THREAD

**Issue by batwicket** [jbmusso/gremlin-javascript#63]
hi..

I am using Jest to unit test and unfortunately it hangs if I instantiate the client. Digging into it, but if you have any insight it would be appreciated.

The setup to reproduce, which is quite minimal, is attached. Uncomment the section in src/ GremlinClient.js to reproduce.
[gremlin.zip](https://github.com/jbmusso/gremlin-javascript/files/587297/gremlin.zip)

thanks

**Comment by jbmusso** [comment]
I never tried to run the test suite with jest. It's meant to run with mocha. Let me know if you have issue running with it.

**Comment by batwicket** [comment]
Perhaps it is because I am running against a live instance of titan-1.0.0-hadoop1. If you don't have time, i'll try to take a look at it. I notice someone was asking for a method to close the websocket connection.. something like this might account the hang. It's specifically due to invoking createClient().

**Comment by batwicket** [comment]
I've just run the v1.0.3 test:node against the current titan-1.0.0-hadoop1 and it is also hanging.

[log.txt](https://github.com/jbmusso/gremlin-javascript/files/589563/log.txt)

**Comment by batwicket** [comment]
If i pull all files from the v1.0.3 test directory except _bootstrap.js and createClient.js then 'gulp test:node' hangs.

**Comment by batwicket** [comment]
If the websocket connection is closed the hang does not occur. I'll submit a pull request later today.

**Comment by batwicket** [comment]
Done. I was able to test it using the v1.0.3 unit tests, but couldn't get them to run on master. It's a very simple change so hopefully not a problem.
