### ISSUE TITLE
unsure how to set the label on a vertex

### ISSUE THREAD

**Issue by batwicket** [jbmusso/gremlin-javascript#64]
hi..

I am trying to set the label on a vertex using addV(), but perhaps have the syntax wrong or maybe I should be using a property like 'name'. The intent is to use a label prefix, such as 'SYS_', to separate the vertices into categories so that access permissions can be easily applied. Probably I've missed some docs. Any help would be appreciated.

The setup to reproduce, which is quite minimal, is attached. The README provides steps.
[gremlin.zip](https://github.com/jbmusso/gremlin-javascript/files/587325/gremlin.zip)

thanks

**Comment by batwicket** [comment]
Not a problem. Issue # 16 addresses this:
`g.addV(label, ${lbl})`

**Comment by jbmusso** [comment]
Glad you figured it out! Feel free to post a [Gist](https://gist.github.com/) or a link to a public repository, rather than a `.zip` file. This is much more convenient :).
