### ISSUE TITLE
"WebSocket closed" when query is large

### ISSUE THREAD

**Issue by guyellis** [jbmusso/gremlin-javascript#71]
If I execute:
```
const query = 'A reasonable amount of gremlin (28,683 bytes)';
client.execute(query, (err, results) => {
...
```
then things work as expected.

For
```
const query = 'A large amount of gremlin (83,696 bytes)';
client.execute(query, (err, results) => {
...
```

I get a `WebSocket closed` error.

What's the limit to the size of the query and any options that can be used to increase that?

**Comment by jbmusso** [comment]
This needs to be configured in the `gremlin-server.yml` file as well :).

**Comment by guyellis** [comment]
Is it the [maxContentLength](https://github.com/apache/tinkerpop/blob/master/gremlin-server/conf/gremlin-server.yaml#L52)?

**Comment by guyellis** [comment]
If that is the setting, is there a way to query the server (from the client using this module) to get back the contents of that file (or this value) to determine the max size of a query?

**Comment by guyellis** [comment]
I just confirmed that upping maxContentLength will solve this problem so closing. (Thanks for response @jbmusso and apologies for asking this here.)

Would love to know if there's a way to get that info back per the previous comment if you know that answer.
