### ISSUE TITLE
OrientDB

### ISSUE THREAD

**Issue by GabCamarda** [jbmusso/gremlin-javascript#75]
Hi,

can this be used with OrientDb?
Thanks,

**Comment by jbmusso** [comment]
It should now that OrientDB officially implements TinkerPop 3. It should work out of the box with Gremlin Server.
Did you have any trouble setting this up?

**Comment by GabCamarda** [comment]
Yes, particularly, Orientdb documentation doesn't talk about setting up the
gremlin server included in the package (if there is any).

Considering you're saying that it is indeed included, how would I connect
to it from the client? By using Orientdb server port? (Tried that, didn't
work)

Thanks

**Comment by jbmusso** [comment]
Just to get a little bit more context, did you have a look at https://github.com/orientechnologies/orientdb-gremlin ?
gremlin-javascript should work out of the box as soon as you manage to start gremlin server properly configured to work with OrientDB. TinkerPop abstracts the database away and gremlin-javascript should work with any database.

**Comment by ThomasKlessen** [comment]
@GabCamarda I'm not sure wehter this is helpful for you, but there is a gremlin.sh/bat within the orientDB/bin folder. I'am using it to play in the comandline with gremlin.
