### ISSUE TITLE
Add client.close() method

### ISSUE THREAD

**Issue by DavidBruant** [jbmusso/gremlin-javascript#9]
Aliasing `client.ws.close()` (to close the client when done with discussing with the API)

Unrelated but I haven't found where the API is documented (at least methods list). Is there such a place?

**Comment by jbmusso** [comment]
You're right that there should be a way to close() the underlying WebSocket connection.

Regarding the API, the main methods are:
* `client.execute(script, bindings, message, callback)` -> this will concatenate all results sent over multiple messages into a single array (`callback(err, results)`).
* `client.stream(script, bindings, message)` -> returns a Stream, each `data` event representing a single result
* `client.messageStream(script, bindings, message)` -> low level variant that does not reemit each result as a distinct `data` event but will emit a `data` event per raw message (depends on the `resultIterationBatchSize` value set in the gremlin server .yaml file).

`bindings` and `message` parameters are optional. You need to pass an empty object `{}` as a second parameter if you wish to set the low level `message` parameter (obviously).

This should be stated more clearly near the top of the Readme.md file in a dedicated section :).

**Comment by benjaminlgt-littlelives** [comment]
Is this the reason node continues running even after the query's execution is completed?

**Comment by masumsoft** [comment]
For me `client.connection.ws.close()` did the trick for version 2.6.0
